global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 1.0
   publish_frequency: 1.0
   width: 30.0
   height: 30.0
   resolution: 0.05
   static_map: true
   rolling_window: false
   cost_scaling_factor: 5.0 
   inflation_radius: 1.0
